### ISSUE TITLE
Low performance

### ISSUE THREAD

**Issue by ssmali1505** [mobilejazz/Motis#20]
Low performance If json data is more than 8mb with combination of multiple custom objects.
For 8mb json, it is near about 30 seconds

**Comment by vilanovi** [comment]
Hello @ssmali1505 ,

Thanks for reporting it. We are currently aware of this issue. The introspection of Obj-c is quite expensive in time. The current version is doing a lot of caching in order to speed it up. However, there are some cases in which is quite expensive.

Our tests, with JSON files of 25mb of size take 1.5 seconds to parse, compared with the 0.5 of the direct assignment. However, your case seems much worse, probably because of the complexity of your custom objects. 

Therefore,  could you give us some detail on how is your json shaped? it would help us to reproduce it and work in order to improve it and make it faster.

Thanks,
